runtime: custom
env: flex
entrypoint: python app.py
module: backend

runtime_config:
  python_version: 3

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 5
  cool_down_period_sec: 180

resources:
  cpu: 1
  memory_gb: 2.0
  disk_size_gb: 10

readiness_check:
  path: "/"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 3600


env_variables:
  GOOGLE_CLOUD_PROJECT: <google_cloud_project>