api_version: 1
runtime: python27
threadsafe: true
instance_class: F1

builtins:
- deferred: true
- remote_api: true

handlers:
- static_dir: static
  url: /static
- login: admin
  script: google.appengine.ext.deferred.deferred.application
  url: /_ah/queue/deferred
- script: main.app
  url: .*
- login: admin
  script: main.app
  url: /admin/.*


libraries:
- name: jinja2
  version: latest
- name: webapp2
  version: 2.5.2
- name: pycrypto
  version: latest
- name: ssl
  version: 2.7.11
- name: PIL
  version: "1.1.7"

