runtime: python27
api_version: 1
threadsafe: yes

instance_class: F2
automatic_scaling:
  max_concurrent_requests: 3
  max_instances: 10

builtins:
- deferred: on

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /static
  static_dir: static

- url: /_ah/queue/deferred
  script: google.appengine.ext.deferred.deferred.application
  login: admin

- url: /.*/tokens
  script: main.app
  login: admin

- url: .*
  script: main.app

libraries:
- name: jinja2
  version: latest
- name: webapp2
  version: "2.5.2"
- name: ssl
  version: latest
- name: PIL
  version: latest

env_variables:
  JWT_SECRET: ""
