api_version: 1

automatic_scaling:
  max_concurrent_requests: 3
  max_instances: 10

builtins:
- deferred: true

env_variables:
  JWT_SECRET:

handlers:
- static_files: favicon.ico
  upload: favicon\.ico
  url: /favicon\.ico
- static_dir: static
  url: /static
- login: admin
  script: google.appengine.ext.deferred.deferred.application
  url: /_ah/queue/deferred
- login: admin
  script: main.app
  url: /.*/tokens
- script: main.app
  url: .*

instance_class: F2

libraries:
- name: jinja2
  version: latest
- name: webapp2
  version: 2.5.2
- name: ssl
  version: latest
- name: PIL
  version: latest

runtime: python27

threadsafe: true
